(() => {
'use strict';
const readabilityHref='readability.css?v=20260729-2';
if(!document.querySelector('link[data-readability-fix]')){const link=document.createElement('link');link.rel='stylesheet';link.href=readabilityHref;link.dataset.readabilityFix='true';document.head.appendChild(link);}
const CART='cw-cart-v3',FAV='cw-favorites-v3',CMP='cw-compare-v3';
const PRODUCTS={
'lavazza-qualita-oro':{name:'Lavazza Qualità Oro',price:1890,image:document.querySelector('[data-add="lavazza-qualita-oro"]')?.closest('.product')?.querySelector('img')?.src},
'delonghi-magnifica-s':{name:'DeLonghi Magnifica S',price:38990,image:document.querySelector('[data-add="delonghi-magnifica-s"]')?.closest('.product')?.querySelector('img')?.src},
'monin-caramel':{name:'Сироп Monin Карамель',price:1190,image:document.querySelector('[data-add="monin-caramel"]')?.closest('.product')?.querySelector('img')?.src},
'timemore-c3':{name:'Timemore Chestnut C3',price:6990,image:document.querySelector('[data-add="timemore-c3"]')?.closest('.product')?.querySelector('img')?.src}};
const get=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const set=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const toast=(m)=>{const n=document.querySelector('[data-toast]');n.textContent=m;n.className='toast show';setTimeout(()=>n.className='toast',2400)};
function counters(){const c=get(CART),f=get(FAV),m=get(CMP);document.querySelectorAll('[data-cart-count]').forEach(n=>n.textContent=c.reduce((s,x)=>s+x.quantity,0));document.querySelectorAll('[data-favorite-count]').forEach(n=>n.textContent=f.length);document.querySelectorAll('[data-compare-count]').forEach(n=>n.textContent=m.length);const total=c.reduce((s,x)=>s+x.price*x.quantity,0);document.querySelectorAll('[data-cart-total-label]').forEach(n=>n.textContent=new Intl.NumberFormat('ru-RU').format(total)+' ₽')}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const id=add.dataset.add,p=PRODUCTS[id],c=get(CART),x=c.find(v=>v.slug===id);x?x.quantity++:c.push({slug:id,name:p.name,price:p.price,image:p.image,quantity:1});set(CART,c);counters();toast(p.name+' добавлен в корзину')}const fav=e.target.closest('[data-favorite]');if(fav){let a=get(FAV),i=a.indexOf(fav.dataset.favorite);i>=0?a.splice(i,1):a.push(fav.dataset.favorite);set(FAV,a);counters();toast(i>=0?'Удалено из избранного':'Добавлено в избранное')}});
document.querySelectorAll('[data-search-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'});toast('Поиск доступен в полном каталоге')});
const megaButton=document.querySelector('[data-mega-trigger]'),mega=document.querySelector('[data-mega]');const setMega=o=>{mega.hidden=!o;megaButton.setAttribute('aria-expanded',String(o))};megaButton.onclick=()=>setMega(mega.hidden);document.addEventListener('click',e=>{if(!mega.hidden&&!mega.contains(e.target)&&!megaButton.contains(e.target))setMega(false)});
const slides=[['Всё для<br>идеального <em>кофе</em>','Кофе в зернах, оборудование, ингредиенты, сиропы и аксессуары. Аренда кофемашин и профессиональный сервис для бизнеса и дома.'],['Кофемашина<br>без лишних <em>затрат</em>','Подберём оборудование по количеству чашек, установим, настроим и возьмём обслуживание на себя.'],['Ваш вкус —<br>наша <em>экспертиза</em>','Подбор кофе по кислотности, насыщенности и способу приготовления. Доставка по Волгограду и России.']];let cur=0;const render=i=>{cur=(i+3)%3;document.querySelector('[data-hero-title]').innerHTML=slides[cur][0];document.querySelector('[data-hero-text]').textContent=slides[cur][1];document.querySelectorAll('[data-slide]').forEach((d,j)=>d.classList.toggle('active',j===cur))};document.querySelector('[data-hero-prev]').onclick=()=>render(cur-1);document.querySelector('[data-hero-next]').onclick=()=>render(cur+1);document.querySelectorAll('[data-slide]').forEach(d=>d.onclick=()=>render(+d.dataset.slide));
const chat=document.querySelector('[data-chat-panel]');document.querySelector('[data-chat-trigger]').onclick=()=>chat.hidden=!chat.hidden;document.querySelector('[data-chat-close]').onclick=()=>chat.hidden=true;
document.querySelectorAll('[data-api-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();if(f.reportValidity()){toast('Заявка отправлена');f.reset();chat.hidden=true}});document.querySelector('[data-subscribe-form]').onsubmit=e=>{e.preventDefault();if(e.currentTarget.reportValidity()){toast('Вы подписались на новости');e.currentTarget.reset()}};counters();
})();